html-skeleton/.npmrc, html-skeleton/index.html
=> Completed the html-skeleton exercise

html-syntax/.npmrc, html-syntax/index.html
=> Finished the html-syntax exercise

html-lists/.npmrc, html-lists/index.html
=> Completed exercise html-lists

css-syntax/.npmrc, css-syntax/index.html, css-syntax/style.css
=> Completed css-syntax exercise

css-pseudo-classes/.npmrc, css-pseudo-classes/index.html, css-pseudo-classes/stylesheet.css
=> Completed css-pseudo-classes exercise

css-fonts/.npmrc, css-fonts/.stylelintrc, css-fonts/index.html, css-fonts/styles.css
=> Compelted the css-fonts exercise

.eslintrc, javascript-primitives-and-variables/.eslintrc, javascript-primitives-and-variables/.npmrc, javascript-primitives-and-variables/index.html, javascript-primitives-and-variables/main.js
=> Javascript primitives and variables

javascript-arrays/.eslintrc, javascript-arrays/.npmrc, javascript-arrays/index.html, javascript-arrays/main.js
=> Completed JavaScript Arrays Exercise

javascript-functions/.eslintrc, javascript-functions/.npmrc, javascript-functions/index.html, javascript-functions/main.js
=> Completed exercise javascript-functions

javascript-loops/.eslintrc, javascript-loops/.npmrc, javascript-loops/index.html, javascript-loops/main.js
=> Completed javascript-loops exercise

javascript-if/.eslintrc, javascript-if/.npmrc, javascript-if/index.html, javascript-if/main.js
=> Completed the javascript-if exercise

javascript-loops-practice/.eslintrc, javascript-loops-practice/.npmrc, javascript-loops-practice/add-suffix-to-all.js, javascript-loops-practice/add-suffix-to-all.test.js, javascript-loops-practice/countdown.js, javascript-loops-practice/countdown.test.js, javascript-loops-practice/filter-out-nulls.js, javascript-loops-practice/filter-out-nulls.test.js, javascript-loops-practice/filter-out-strings.js, javascript-loops-practice/filter-out-strings.test.js, javascript-loops-practice/find-index.js, javascript-loops-practice/find-index.test.js, javascript-loops-practice/get-indexes.js, javascript-loops-practice/get-indexes.test.js, javascript-loops-practice/get-student-names.js, javascript-loops-practice/get-student-names.test.js, javascript-loops-practice/includes-seven.js, javascript-loops-practice/includes-seven.test.js, javascript-loops-practice/index.html, javascript-loops-practice/odd-or-even.js, javascript-loops-practice/odd-or-even.test.js, javascript-loops-practice/sum-all.js, javascript-loops-practice/sum-all.test.js
THAT WAS TOUGH!!! WHOOP WHOOP LETS GOOOO
=> Completed the javascript-loops-practice exercise

array-manipulation-1/.eslintrc, array-manipulation-1/.npmrc, array-manipulation-1/index.html, array-manipulation-1/src/ban-methods.js, array-manipulation-1/src/compact.js, array-manipulation-1/src/compact.test.js, array-manipulation-1/src/head.js, array-manipulation-1/src/head.test.js, array-manipulation-1/src/initial.js, array-manipulation-1/src/initial.test.js, array-manipulation-1/src/last.js, array-manipulation-1/src/last.test.js, array-manipulation-1/src/reverse.js, array-manipulation-1/src/reverse.test.js, array-manipulation-1/src/tail.js, array-manipulation-1/src/tail.test.js
=> Completed manipulating arrays

string-manipulation-1/.eslintrc, string-manipulation-1/.npmrc, string-manipulation-1/index.html, string-manipulation-1/src/ban-methods.js, string-manipulation-1/src/capitalize.js, string-manipulation-1/src/capitalize.test.js, string-manipulation-1/src/get-first-char.js, string-manipulation-1/src/get-first-char.test.js, string-manipulation-1/src/get-last-char.js, string-manipulation-1/src/get-last-char.test.js, string-manipulation-1/src/get-words.js, string-manipulation-1/src/get-words.test.js, string-manipulation-1/src/is-lower-cased.js, string-manipulation-1/src/is-lower-cased.test.js, string-manipulation-1/src/is-upper-cased.js, string-manipulation-1/src/is-upper-cased.test.js, string-manipulation-1/src/is-vowel.js, string-manipulation-1/src/is-vowel.test.js, string-manipulation-1/src/reverse-word.js, string-manipulation-1/src/reverse-word.test.js
=> Completed manipulating strings

dom-querying/.eslintrc, dom-querying/.npmrc, dom-querying/index.html, dom-querying/main.js
=> Completed the dom-querying exercise

dom-events/.eslintrc, dom-events/.npmrc, dom-events/buttons.html, dom-events/buttons.js, dom-events/document.html, dom-events/document.js, dom-events/styles.css
=> Completed dom events exercise

javascript-light-bulb/.npmrc, javascript-light-bulb/index.html, javascript-light-bulb/main.js, javascript-light-bulb/styles.css
=> Completed the JavaScript Light Bulb exercise

css-transitions/index.html
=> Need to recommit, merged accidentally

javascript-forms/.eslintrc, javascript-forms/.npmrc, javascript-forms/form-events.html, javascript-forms/form-events.js, javascript-forms/form-values.html, javascript-forms/form-values.js, javascript-forms/styles.css
=> Completed the JavaScript Forms exercise

dom-event-delegation/.eslintrc, dom-event-delegation/.npmrc, dom-event-delegation/index.html, dom-event-delegation/main.js, dom-event-delegation/styles.css
=> Completed the dom-event-delgation exercise

javascript-and-json/.eslintrc, javascript-and-json/.npmrc, javascript-and-json/index.html, javascript-and-json/main.js
=> Compelted the javascript-and-json exercise

javascript-modal/.npmrc, javascript-modal/index.html, javascript-modal/main.js, javascript-modal/styles.css
=> Completed JavaScript Modal Exercise

javascript-local-storage/.eslintrc, javascript-local-storage/.npmrc, javascript-local-storage/data.js, javascript-local-storage/index.html, javascript-local-storage/main.js, javascript-local-storage/styles.css
=> Completed the javascript-local-storage exercise

object-manipulation-1/.eslintrc, object-manipulation-1/.npmrc, object-manipulation-1/index.html, object-manipulation-1/src/ban-methods.js, object-manipulation-1/src/get-keys.js, object-manipulation-1/src/get-keys.test.js, object-manipulation-1/src/get-value.js, object-manipulation-1/src/get-value.test.js, object-manipulation-1/src/get-values.js, object-manipulation-1/src/get-values.test.js, object-manipulation-1/src/set-value.js, object-manipulation-1/src/set-value.test.js, object-manipulation-1/src/to-object.js, object-manipulation-1/src/to-object.test.js
=> Completed object-manipulation-1 exercise

javascript-custom-methods/.eslintrc, javascript-custom-methods/.npmrc, javascript-custom-methods/calculator.js, javascript-custom-methods/calculator.test.js, javascript-custom-methods/doggo.js, javascript-custom-methods/doggo.test.js, javascript-custom-methods/event-target.js, javascript-custom-methods/index.html, javascript-custom-methods/test.html
=> Completed JavaScript Custom Methods Exercise

javascript-constructors/.eslintrc, javascript-constructors/.npmrc, javascript-constructors/example-constructor.html, javascript-constructors/example-constructor.js, javascript-constructors/index.html, javascript-constructors/new-objects.html, javascript-constructors/new-objects.js, javascript-constructors/stopwatch.html, javascript-constructors/stopwatch.js, javascript-constructors/student.js, javascript-constructors/student.test.js, javascript-constructors/test.html
=> Completed all tests for JavaScript Constructors.

javascript-timers/.npmrc, javascript-timers/interval.html, javascript-timers/interval.js, javascript-timers/timeout.html, javascript-timers/timeout.js
=> Completed timeout and interval exercises for JavaScript Timers

javascript-ajax/.eslintrc, javascript-ajax/.npmrc, javascript-ajax/pokemon.html, javascript-ajax/pokemon.js, javascript-ajax/users.html, javascript-ajax/users.js
=> Completed JavaScript AJAX exercise

sql-select/.npmrc, sql-select/actor-forty.sql, sql-select/actor-names.sql, sql-select/all-actors.sql, sql-select/all-categories.sql, sql-select/all-customers.sql, sql-select/all-films.sql, sql-select/all-languages.sql, sql-select/cheap-to-rent.sql, sql-select/expensive-films.sql, sql-select/five-customer-emails.sql, sql-select/inactive-customers.sql, sql-select/r-rated-films.sql, sql-select/second-store-customers.sql, sql-select/ten-actor-first-names.sql, sql-select/twenty-films-of-06.sql, sql-select/two-kilmers.sql, sql-select/west-bengali-postal-codes.sql
Screenshot of sql-select directory
=> completed sql-select exercise

sql-update/.npmrc, sql-update/make-yoder.sql, sql-update/murica.sql, sql-update/sick-prank.sql
=> compelted sql-update exercise

sql-delete/.npmrc, sql-delete/bizarre.sql, sql-delete/diplomat.sql, sql-delete/puritanical.sql, sql-delete/sanction.sql
Screenshot of terminal with intended error for puritanical.sql
=> compelted sql-delete exercise

.gitignore, string-manipulation-2/.eslintrc, string-manipulation-2/.npmrc, string-manipulation-2/index.html, string-manipulation-2/src/capitalize-word.js, string-manipulation-2/src/capitalize-word.test.js, string-manipulation-2/src/capitalize-words.js, string-manipulation-2/src/capitalize-words.test.js, string-manipulation-2/src/first-chars.js, string-manipulation-2/src/first-chars.test.js, string-manipulation-2/src/last-chars.js, string-manipulation-2/src/last-chars.test.js, string-manipulation-2/src/num-vowels.js, string-manipulation-2/src/num-vowels.test.js, string-manipulation-2/src/ransom-case.js, string-manipulation-2/src/ransom-case.test.js, string-manipulation-2/src/swap-chars.js, string-manipulation-2/src/swap-chars.test.js, string-manipulation-2/src/truncate.js, string-manipulation-2/src/truncate.test.js
=> String manipulation 2

express-error-handling/.env.example, express-error-handling/.gitignore, express-error-handling/.npmrc, express-error-handling/database/data.sql, express-error-handling/database/schema.sql, express-error-handling/package.json, express-error-handling/scripts/db-import.bash, express-error-handling/server/client-error.js, express-error-handling/server/error-middleware.js, express-error-handling/server/index.js, fetch-in-react-practice/.env
=> completed express-error-handling exercise

api-registration/.env.example, api-registration/.eslintrc, api-registration/.gitignore, api-registration/.npmrc, api-registration/database/data.sql, api-registration/database/schema.sql, api-registration/hash-password.js, api-registration/package.json, api-registration/scripts/db-import.bash, api-registration/server/client-error.js, api-registration/server/error-middleware.js, api-registration/server/index.js, express-error-handling/.env
=> completed api-registration exercise

javascript-closures/.eslintrc, javascript-closures/.npmrc, javascript-closures/index.html, javascript-closures/main.js, javascript-closures/make-adder.html, javascript-closures/make-counter.html, javascript-closures/make-sizer.html, react-context/.env, react-context/flow.txt
=> completed javascript-closures exercise

api-authentication/.env, api-authorization/.env.example, api-authorization/.eslintrc, api-authorization/.gitignore, api-authorization/.npmrc, api-authorization/database/data.sql, api-authorization/database/schema.sql, api-authorization/package.json, api-authorization/scripts/db-import.bash, api-authorization/server/authorization-middleware.js, api-authorization/server/client-error.js, api-authorization/server/error-middleware.js, api-authorization/server/index.js, api-authorization/verify-token.js
=> completed api-authorizatio challenge

working-with-collections/.eslintrc, working-with-collections/.npmrc, working-with-collections/index.html, working-with-collections/main.js
=> Working with collections
